# הגדרת החיבור ל-MySQL ב-Clever Cloud
spring.datasource.url=jdbc:mysql://bjdrlq3deqvyn2fc2w10-mysql.services.clever-cloud.com:3306/bjdrlq3deqvyn2fc2w10
spring.datasource.username=ukfjut8zi3iv2xlb
spring.datasource.password=NNcxdBJedBUkhp7CqVaW

# הגדרת הדרייבר
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=3
# הגדרות Hibernate - יצירת טבלאות ועדכון מבנה אוטומטי
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# הגדרה לפורט של השרת (חשוב להעלאה ל-Render בהמשך)
server.port=${PORT:8080}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=m79359650@gmail.com
spring.mail.password=hsmu xdgm pfuc ntzu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true